# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-19 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180514_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomments',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
